// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJgJNBL8t2v9seZhlTdUTNL26Cvw55ofs',
    appId: '1:104650394084:web:21a2531805911543d0dff1',
    messagingSenderId: '104650394084',
    projectId: 'track-order-2468c',
    authDomain: 'track-order-2468c.firebaseapp.com',
    storageBucket: 'track-order-2468c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAINqHA4KKZMVTI-bDha9jAUUGXFfdS0Rk',
    appId: '1:104650394084:android:86ce3413d0527b4dd0dff1',
    messagingSenderId: '104650394084',
    projectId: 'track-order-2468c',
    storageBucket: 'track-order-2468c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5DGyzWc2oLbXaDASTmUNAzAE_ntSUUb0',
    appId: '1:104650394084:ios:c38eed83258b6204d0dff1',
    messagingSenderId: '104650394084',
    projectId: 'track-order-2468c',
    storageBucket: 'track-order-2468c.appspot.com',
    iosBundleId: 'com.example.orderTrack',
  );
}
